name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods
      run: pod install
    - name: Test
      run: xcodebuild test -workspace HwpMac.xcworkspace -scheme HwpMac -enableCodeCoverage YES -resultBundlePath HwpMac.xcresult | xcpretty
    - name: Report
      run: xcrun xccov view --report --json HwpMac.xcresult > coverage.json 
    - name: Upload code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageLocations: |
          ${{github.workspace}}/coverage.json:json
