name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods
      run: pod install
    - name: Test
      run: xcodebuild test -workspace HwpMac.xcworkspace -scheme HwpMac -enableCodeCoverage YES -resultBundlePath HwpMac.xcresult | xcpretty
